package orange_team.chatting.DomainObjects;

import org.springframework.data.annotation.Version;

import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;

@Entity
public class Poster {
    @Id
    //@GeneratedValue(strategy = GenerationType.AUTO)
    //nueva update, ahora si lo marcas como autogenerated y lo llenas antes de guardar,
    //lo toma como que alguien lo borro. Verdaderamente una genial decicion
    //sobretodo la parte de hacerlo sin actualizar el tutorial de como usar esto. 
    //La verdad me queda mucho que aprender de las mentes brillantes detras de spring
    private String idName;
    private String pName;
    private String codedPassword;
    private String email;

    protected Poster() {}

    public Poster(String id_name, String p_name, String coded_Password, String Email)
    {
        this.idName = id_name;
        this.pName = p_name;
        this.codedPassword = coded_Password;
        this.email = Email;
    }
    @Override
    public String toString()
    {
        return String.format("Poster( id_name = %s, p_name = %s, coded_password = %s, e-mail = %s)", 
        idName, pName, codedPassword, email != null ? email : "no e-mail provided");
    }
    
    public void setIdName(String id_name) {this.idName = id_name;}
    public void setPName(String p_name) {this.pName = p_name;}
    public void setCodedPassword(String coded_Password) {this.codedPassword = coded_Password;}
    public void setEmail(String Email) {this.email = Email;}

    public String getIdName() {return idName;}
    public String getPName() {return pName;}
    public String getCodedPassword() {return codedPassword;}
    public String getEmail() {return email;}
}
